# Generated by Django 3.2.5 on 2021-08-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', '-created']},
        ),
        migrations.AddField(
            model_name='message',
            name='read_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
