# Generated by Django 3.2.5 on 2021-08-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_auto_20210802_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_on',
        ),
    ]
