# Generated by Django 3.2.5 on 2021-07-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210724_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('Liked', 'Like'), ('Disliked', 'Dislike')], max_length=10),
        ),
    ]
